name: ui-test
on: [push]

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
     
      # build frontend
      - name: Cache NPM Modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-npm
        with:
          path: ./node_modules/
          key: cache-npm-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: yarn install
    
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: yarn test:ui

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
